//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminsystem_Canteen
    {
        public int admin_ID { get; set; }
        public string adminname { get; set; }
        public Nullable<int> admin_level_id { get; set; }
        public string password1 { get; set; }
        public string name { get; set; }
        public string Ternsubcode { get; set; }
        public string Terncode { get; set; }
        public Nullable<int> loginflag { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
    }
}
