//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmSM
    {
        public int AlarmID { get; set; }
        public int AlarmVerifyID { get; set; }
        public int SMSID { get; set; }
        public string subject { get; set; }
        public string Detail { get; set; }
        public string SMSNumber { get; set; }
        public string Provider { get; set; }
        public string Username { get; set; }
    }
}
