//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        public int AlarmID { get; set; }
        public string AlarmVerifyName { get; set; }
        public int AlarmVerifyId { get; set; }
        public string OutputDeviceIP { get; set; }
        public Nullable<int> OutputPort { get; set; }
        public Nullable<int> AlarmSoundID { get; set; }
        public Nullable<int> EmailID { get; set; }
        public string Description { get; set; }
        public string Subject { get; set; }
        public string Detail { get; set; }
        public Nullable<int> PanelShow { get; set; }
        public Nullable<int> SoundON { get; set; }
        public Nullable<int> EmailSend { get; set; }
        public Nullable<int> AlarmIO { get; set; }
        public Nullable<int> Smssend { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Check { get; set; }
    }
}
