//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmZoneList
    {
        public int AlarmID { get; set; }
        public int DoorID { get; set; }
        public string DoorName { get; set; }
        public Nullable<int> ServerID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> SubDoor { get; set; }
    }
}
