//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmIO
    {
        public int AlarmIOID { get; set; }
        public string AlarmIOName { get; set; }
        public Nullable<int> AlarmOutPutDevice { get; set; }
        public Nullable<int> AlarmOutputPort { get; set; }
        public string AlarmOutputIP { get; set; }
        public Nullable<int> AlarmOutputDuration { get; set; }
        public Nullable<int> AlarmOutputDelay { get; set; }
        public Nullable<int> AlarmIONumber { get; set; }
        public Nullable<int> Status { get; set; }
        public int IOID { get; set; }
        public int IO { get; set; }
        public string IPAddress { get; set; }
        public string Port { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public byte[] PictureON { get; set; }
        public byte[] PictureOFF { get; set; }
        public Nullable<int> PictureIndex { get; set; }
        public string Type { get; set; }
    }
}
