//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmIOLink
    {
        public int AlarmID { get; set; }
        public int AlarmIOID { get; set; }
        public int AlarmVerifyID { get; set; }
        public string AlarmIOName { get; set; }
        public string AlarmMemo { get; set; }
    }
}
