//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmEvent
    {
        public int autoID { get; set; }
        public string CardID { get; set; }
        public string EmproyeID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string DeviceName { get; set; }
        public string Event { get; set; }
        public Nullable<int> clear { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> SubDoor { get; set; }
        public string FunctionKey { get; set; }
        public Nullable<System.DateTime> Logstime { get; set; }
    }
}
