//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmSound
    {
        public int AlarmSoundID { get; set; }
        public string AlarmSoundName { get; set; }
        public Nullable<int> AlarmDuration { get; set; }
        public Nullable<int> AlarmDelay { get; set; }
        public Nullable<int> AlarmHi { get; set; }
        public Nullable<int> AlarmLo { get; set; }
        public byte[] AlarmWave { get; set; }
        public string AlarmWaveFile { get; set; }
    }
}
