//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canteen_device
    {
        public int TID { get; set; }
        public Nullable<int> Store_ID { get; set; }
        public string TID_N { get; set; }
        public string location { get; set; }
        public string IpAddress { get; set; }
    }
}
