//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canteen_Editdata
    {
        public int Runno { get; set; }
        public string Empid { get; set; }
        public Nullable<System.DateTime> Event_date { get; set; }
        public string Terminal_sn { get; set; }
        public string FileMemo { get; set; }
        public Nullable<float> OldMoney { get; set; }
        public Nullable<float> NewMoney { get; set; }
        public string EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditStatus { get; set; }
    }
}
