//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTV_Zone_Detail
    {
        public int CCTVZoneID { get; set; }
        public int CCTVID { get; set; }
        public string Memo { get; set; }
        public byte[] Pic { get; set; }
    }
}
