//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_Pic
    {
        public int PictureIndex { get; set; }
        public byte[] PictureOn { get; set; }
        public byte[] PictureOff { get; set; }
        public string Memo1 { get; set; }
    }
}
