//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorList
    {
        public int DoorID { get; set; }
        public string DoorName { get; set; }
        public int ServerID { get; set; }
        public int SubDoor { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> status { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> PosX { get; set; }
        public Nullable<int> PosY { get; set; }
        public string Access { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<int> VERIFYCODE { get; set; }
        public string SENSORID { get; set; }
        public string ck { get; set; }
        public Nullable<int> Functionkey { get; set; }
        public Nullable<int> resv1 { get; set; }
        public Nullable<int> resv2 { get; set; }
        public string type1 { get; set; }
        public string Badgenumber { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string USERID { get; set; }
        public Nullable<int> ReaderIN { get; set; }
        public Nullable<int> ReaderOut { get; set; }
        public string MainType { get; set; }
        public string ServerName { get; set; }
        public Nullable<int> ServerPort { get; set; }
        public Nullable<int> Inzone { get; set; }
        public Nullable<int> Outzone { get; set; }
        public byte[] PictureOn { get; set; }
        public byte[] PictureOff { get; set; }
        public Nullable<int> PictureIndex { get; set; }
        public string Type { get; set; }
        public Nullable<int> CamaraZoneID { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public Nullable<int> UserLimitUpper { get; set; }
        public Nullable<int> LimitUpper { get; set; }
        public Nullable<int> UpperTime { get; set; }
        public Nullable<int> UserLimitLower { get; set; }
        public Nullable<int> LimitLower { get; set; }
        public Nullable<int> LowerTime { get; set; }
        public Nullable<int> UserLimit { get; set; }
        public Nullable<int> LimitActive { get; set; }
        public Nullable<int> LimitTime { get; set; }
        public Nullable<int> Empnum { get; set; }
        public Nullable<int> Carnum { get; set; }
        public string Caruserid { get; set; }
        public string IOIP { get; set; }
        public Nullable<int> IOPort { get; set; }
        public Nullable<int> IOIO { get; set; }
        public Nullable<int> IOTime { get; set; }
        public string Cctvin { get; set; }
        public string Cctvin2 { get; set; }
        public string Cctvout { get; set; }
        public string Cctvout2 { get; set; }
        public Nullable<int> Statusgate { get; set; }
        public Nullable<int> DoorType { get; set; }
        public Nullable<int> UseCyt { get; set; }
        public Nullable<int> Loc_id { get; set; }
    }
}
