//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventStamp
    {
        public int ID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> Event_date { get; set; }
        public Nullable<int> LimiteStamp { get; set; }
        public Nullable<int> StampNo { get; set; }
        public Nullable<int> TID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Used { get; set; }
        public string StampCode { get; set; }
        public string StampcodeM { get; set; }
    }
}
