//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormatTextfile
    {
        public int AutoID { get; set; }
        public string FormatID { get; set; }
        public string FormatText { get; set; }
        public string Addzero { get; set; }
        public Nullable<int> Rangeoftime { get; set; }
        public Nullable<int> Grouptime { get; set; }
        public Nullable<int> Alllog { get; set; }
        public Nullable<int> checkfunction { get; set; }
        public Nullable<int> Firstall { get; set; }
        public string CutDigit { get; set; }
        public string MarkExport { get; set; }
        public string ExportAllDoor { get; set; }
        public string DefineFLTime { get; set; }
        public Nullable<System.DateTime> Ftime { get; set; }
        public Nullable<System.DateTime> Ltime { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public Nullable<System.DateTime> D1 { get; set; }
        public Nullable<System.DateTime> D2 { get; set; }
        public Nullable<System.DateTime> D3 { get; set; }
        public Nullable<System.DateTime> D4 { get; set; }
        public Nullable<System.DateTime> D5 { get; set; }
        public Nullable<System.DateTime> D6 { get; set; }
        public Nullable<int> I1 { get; set; }
        public Nullable<int> I2 { get; set; }
        public Nullable<int> I3 { get; set; }
        public Nullable<int> I4 { get; set; }
        public Nullable<int> I5 { get; set; }
        public Nullable<int> I6 { get; set; }
        public Nullable<int> I7 { get; set; }
        public Nullable<int> I8 { get; set; }
    }
}
