//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTPServer1
    {
        public string IpAddress { get; set; }
        public string Username1 { get; set; }
        public string Password1 { get; set; }
        public Nullable<int> Type1 { get; set; }
        public string Zdesc { get; set; }
    }
}
