//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayType
    {
        public Nullable<byte> HolidayType1 { get; set; }
        public string Note { get; set; }
        public Nullable<double> NormalRate { get; set; }
        public Nullable<double> OTRate { get; set; }
        public bool HolidayRelax { get; set; }
    }
}
