//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportFormat
    {
        public int Type1 { get; set; }
        public string Textfile { get; set; }
        public string symbol { get; set; }
        public string rowstart { get; set; }
        public string column { get; set; }
    }
}
