//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class includevacation
    {
        public string UserID { get; set; }
        public int year1 { get; set; }
        public int cpreyear { get; set; }
        public Nullable<int> cthisyear { get; set; }
        public string closeyear { get; set; }
        public string Badgenumber { get; set; }
    }
}
