//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRecord
    {
        public int LID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public Nullable<int> TotalDay { get; set; }
        public Nullable<System.DateTime> TotalHour { get; set; }
        public Nullable<System.DateTime> RecordTime { get; set; }
        public Nullable<byte> LeavePay { get; set; }
        public string Docno { get; set; }
        public string Docgaruntee { get; set; }
        public string cause { get; set; }
        public string Badgenumber { get; set; }
    }
}
