//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVECLASS1
    {
        public int LEAVEID { get; set; }
        public string LEAVENAME { get; set; }
        public double MINUNIT { get; set; }
        public int UNIT { get; set; }
        public int REMAINDPROC { get; set; }
        public int REMAINDCOUNT { get; set; }
        public string REPORTSYMBOL { get; set; }
        public double DEDUCT { get; set; }
        public int LEAVETYPE { get; set; }
        public int COLOR { get; set; }
        public int CLASSIFY { get; set; }
        public string CALC { get; set; }
    }
}
