//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveID
    {
        public int ID { get; set; }
        public Nullable<int> LeaveID1 { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public Nullable<int> hourOfLeave { get; set; }
        public Nullable<int> authorize { get; set; }
        public Nullable<int> LeaveFormNumber { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
