//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machinedetail1
    {
        public int ServerID { get; set; }
        public string TLCD { get; set; }
        public string Tdes { get; set; }
        public Nullable<int> FPmode { get; set; }
        public Nullable<int> Acces { get; set; }
        public Nullable<int> Master { get; set; }
        public string IPMaster { get; set; }
        public Nullable<int> Acs { get; set; }
        public Nullable<int> ERead { get; set; }
        public Nullable<int> WGInF { get; set; }
        public Nullable<int> WGOut { get; set; }
        public Nullable<int> WGOutF { get; set; }
        public string MTime { get; set; }
        public Nullable<int> CDisp { get; set; }
        public Nullable<int> Dclock { get; set; }
        public Nullable<int> ClockInt { get; set; }
        public Nullable<int> KeyIN { get; set; }
        public Nullable<int> IAE { get; set; }
        public Nullable<int> Late { get; set; }
        public Nullable<int> FKMode { get; set; }
        public Nullable<int> LCDTime { get; set; }
        public string submask { get; set; }
        public string gateway { get; set; }
        public string DNSserver { get; set; }
        public Nullable<int> cmode { get; set; }
        public string pw { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> Dup { get; set; }
        public string AAC { get; set; }
        public string APW { get; set; }
        public string Uac { get; set; }
        public string UPW { get; set; }
        public Nullable<int> AdminID1 { get; set; }
        public Nullable<int> AdminID2 { get; set; }
        public Nullable<int> AdminID3 { get; set; }
        public Nullable<int> AdminID4 { get; set; }
        public Nullable<int> AdminID5 { get; set; }
        public string Serial { get; set; }
        public string D1Location { get; set; }
        public Nullable<int> D1OT { get; set; }
        public Nullable<int> D1LRT { get; set; }
        public Nullable<int> D1CPTz { get; set; }
        public Nullable<int> D1UTZ { get; set; }
        public Nullable<int> D1BOTz { get; set; }
        public Nullable<int> D1FPTz { get; set; }
        public Nullable<int> D1APBL { get; set; }
        public Nullable<int> D1RTr { get; set; }
        public Nullable<int> D1DTy { get; set; }
        public Nullable<int> D1Rty { get; set; }
        public Nullable<int> D1RI { get; set; }
        public Nullable<int> D1DBTz { get; set; }
        public Nullable<int> D1DBAp { get; set; }
        public Nullable<int> D1Rec { get; set; }
        public Nullable<int> D1Resv { get; set; }
        public Nullable<int> APBable { get; set; }
        public Nullable<int> APBTime { get; set; }
        public Nullable<int> DualDoor { get; set; }
        public Nullable<int> ADable { get; set; }
        public Nullable<int> ADPw { get; set; }
        public Nullable<int> D1DOTLRelay { get; set; }
        public Nullable<int> D1DOTLTime { get; set; }
        public Nullable<int> D1UnATZRelay { get; set; }
        public Nullable<int> D1UnATZTime { get; set; }
        public Nullable<int> D1APRejectRelay { get; set; }
        public Nullable<int> D1APRejectTime { get; set; }
        public Nullable<int> D1IntrudedRelay { get; set; }
        public Nullable<int> D1IntrudedTime { get; set; }
        public Nullable<int> D1TamperRelay { get; set; }
        public Nullable<int> D1TamperTime { get; set; }
        public Nullable<int> D1AntiDuressRelay { get; set; }
        public Nullable<int> D1AntiDuressTime { get; set; }
        public Nullable<int> active { get; set; }
        public string memo { get; set; }
        public Nullable<int> D1FCCTz { get; set; }
        public Nullable<int> D1FCTz { get; set; }
        public Nullable<int> D1Ctz { get; set; }
        public Nullable<int> D1Ftz { get; set; }
        public Nullable<int> D1revs1 { get; set; }
        public Nullable<int> D1revs2 { get; set; }
        public Nullable<int> D1revs3 { get; set; }
        public Nullable<int> LCD { get; set; }
        public Nullable<int> Keye { get; set; }
        public Nullable<int> badge { get; set; }
    }
}
