//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineList
    {
        public int ID { get; set; }
        public string MachineAlias { get; set; }
        public Nullable<int> ConnectType { get; set; }
        public string IPOrCommPort { get; set; }
        public string PortOrBaudrate { get; set; }
        public Nullable<int> MachineNum { get; set; }
        public int ServerID { get; set; }
        public string ServerCode { get; set; }
        public Nullable<int> RegUsers { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Security_level { get; set; }
        public string Device_Name { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public string Comm { get; set; }
        public string IP_address { get; set; }
        public string Port { get; set; }
        public string Modem_Port { get; set; }
        public string Modem_Phone { get; set; }
        public string COM_Port { get; set; }
        public Nullable<int> TempSize { get; set; }
        public Nullable<int> Active { get; set; }
        public string BFM { get; set; }
        public string Mtran { get; set; }
        public string EXtran { get; set; }
        public string TMtran { get; set; }
        public string TExtran { get; set; }
        public string BFD1 { get; set; }
        public string DI1 { get; set; }
        public string DO1 { get; set; }
        public string TI1 { get; set; }
        public string TO1 { get; set; }
        public string BFD2 { get; set; }
        public string DI2 { get; set; }
        public string DO2 { get; set; }
        public string TI2 { get; set; }
        public string TO2 { get; set; }
        public string BFD3 { get; set; }
        public string DI3 { get; set; }
        public string DO3 { get; set; }
        public string TI3 { get; set; }
        public string TO3 { get; set; }
        public string BFD4 { get; set; }
        public string DI4 { get; set; }
        public string DO4 { get; set; }
        public string TI4 { get; set; }
        public string TO4 { get; set; }
        public string BFD5 { get; set; }
        public string DI5 { get; set; }
        public string DO5 { get; set; }
        public string TI5 { get; set; }
        public string TO5 { get; set; }
        public string BFD6 { get; set; }
        public string DI6 { get; set; }
        public string DO6 { get; set; }
        public string TI6 { get; set; }
        public string TO6 { get; set; }
        public string BFD7 { get; set; }
        public string DI7 { get; set; }
        public string DO7 { get; set; }
        public string TI7 { get; set; }
        public string TO7 { get; set; }
        public string BFD8 { get; set; }
        public string DI8 { get; set; }
        public string DO8 { get; set; }
        public string TI8 { get; set; }
        public string TO8 { get; set; }
        public Nullable<int> d0 { get; set; }
        public Nullable<int> d1 { get; set; }
        public Nullable<int> d2 { get; set; }
        public Nullable<int> d3 { get; set; }
        public Nullable<int> d4 { get; set; }
        public Nullable<int> d5 { get; set; }
        public Nullable<int> d6 { get; set; }
        public Nullable<int> d7 { get; set; }
        public Nullable<int> d8 { get; set; }
        public Nullable<int> MasteTID { get; set; }
        public string Master_IP { get; set; }
        public Nullable<int> Antipass { get; set; }
        public Nullable<int> ToleranceTime { get; set; }
        public Nullable<int> DualAll { get; set; }
        public Nullable<int> Zone_id { get; set; }
        public Nullable<int> X_Map { get; set; }
        public Nullable<int> Y_Map { get; set; }
        public string CKUse { get; set; }
        public string password { get; set; }
        public string comkey { get; set; }
        public Nullable<int> timeout { get; set; }
        public Nullable<int> DGroup { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public Nullable<int> Dstatus { get; set; }
        public string serveridcode { get; set; }
        public Nullable<int> AccessType { get; set; }
        public Nullable<int> TickCount { get; set; }
        public Nullable<int> onlinestatus { get; set; }
        public Nullable<int> MDTime { get; set; }
        public string tabletid { get; set; }
        public string tabletport { get; set; }
        public string PrinterName { get; set; }
        public Nullable<int> Gatezone { get; set; }
        public Nullable<int> Equip_ID { get; set; }
        public string Cartype { get; set; }
    }
}
