//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapZone
    {
        public int Zone_id { get; set; }
        public string ZoneName { get; set; }
        public byte[] PicZone { get; set; }
        public string CKUse { get; set; }
    }
}
