//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapZoneDetail2
    {
        public int Zone_id { get; set; }
        public int AlarmIOID { get; set; }
        public int AlarmINPort { get; set; }
        public Nullable<int> AlarmDeviceID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> X_Map { get; set; }
        public Nullable<int> Y_Map { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> Level { get; set; }
        public string maintype { get; set; }
        public Nullable<int> ReaderIN { get; set; }
        public Nullable<int> ReaderOut { get; set; }
        public string Device_Name { get; set; }
        public Nullable<int> IOID { get; set; }
    }
}
