//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSLogCredit
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Credit { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> activeDate { get; set; }
        public Nullable<System.DateTime> StampDate { get; set; }
    }
}
