//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSLog
    {
        public int ID { get; set; }
        public string BILLID { get; set; }
        public string Trn_id { get; set; }
        public Nullable<int> itemno { get; set; }
        public Nullable<System.DateTime> DateIN { get; set; }
        public Nullable<System.DateTime> ServerDate { get; set; }
        public string CardID { get; set; }
        public string BadgeNumebr { get; set; }
        public string FunctionKey { get; set; }
        public string ck { get; set; }
        public Nullable<int> Used { get; set; }
        public Nullable<int> Topup { get; set; }
        public Nullable<System.DateTime> Topupdate { get; set; }
        public Nullable<int> remain { get; set; }
        public Nullable<int> TID { get; set; }
        public string TopupAdmin { get; set; }
        public string TopupPurpose { get; set; }
        public string UsePurpose { get; set; }
        public string TopupTID { get; set; }
        public string UseTID { get; set; }
        public string TranID { get; set; }
        public Nullable<int> Mv_id { get; set; }
        public Nullable<int> CkLimit { get; set; }
        public Nullable<int> ItemSum { get; set; }
        public Nullable<int> sumTotal { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> RunningNo { get; set; }
    }
}
