//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSticker
    {
        public int StickerGp { get; set; }
        public string StickerGpName { get; set; }
        public Nullable<int> Topup { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<int> StartDate { get; set; }
        public Nullable<int> ST_RW { get; set; }
        public Nullable<int> RW_ST { get; set; }
        public string Smemo { get; set; }
        public Nullable<int> CarryForward { get; set; }
        public Nullable<int> Dlimit { get; set; }
    }
}
