//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTopup
    {
        public int Month { get; set; }
        public int Year { get; set; }
        public int StickerGP { get; set; }
        public Nullable<int> StickerTopup { get; set; }
        public Nullable<int> CK { get; set; }
    }
}
