//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUM_RUN_HOL
    {
        public int NUM_RUNID { get; set; }
        public byte HolidayType { get; set; }
        public bool HolidayRelax { get; set; }
    }
}
