//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriod
    {
        public int PPNum { get; set; }
        public string PayName { get; set; }
        public Nullable<byte> DayStart { get; set; }
        public Nullable<short> MonthStart { get; set; }
        public Nullable<byte> DayStop { get; set; }
        public Nullable<short> MonthStop { get; set; }
    }
}
