//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pk_api_function
    {
        public int fn_api_id { get; set; }
        public string fu { get; set; }
        public Nullable<int> require_Token { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
