//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PK_ErrorLog
    {
        public int ID { get; set; }
        public string Cscmain_ID { get; set; }
        public Nullable<System.DateTime> xDatetime { get; set; }
        public string Description { get; set; }
        public Nullable<int> Gate_ID { get; set; }
        public string Carid { get; set; }
        public string Scr_No { get; set; }
    }
}
