//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PK_stampConditionCodeSub
    {
        public int ID { get; set; }
        public Nullable<int> PKStampConditioncode { get; set; }
        public Nullable<int> ShoppingValue { get; set; }
        public string Stampcode { get; set; }
        public string Cartype1 { get; set; }
        public Nullable<int> Cartype { get; set; }
        public Nullable<int> SV_Max { get; set; }
    }
}
