//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkadminweblog
    {
        public int LogID { get; set; }
        public string Adminname { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string PRG { get; set; }
        public string Topic { get; set; }
        public string SubTopic { get; set; }
        public Nullable<int> ActionFlag { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Memo { get; set; }
        public string Deviceno { get; set; }
        public Nullable<int> AdminLevel { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public string table1 { get; set; }
        public string keyid { get; set; }
        public Nullable<int> sf { get; set; }
        public Nullable<System.DateTime> Syndate { get; set; }
    }
}
