//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKAdminsystem_levelsub
    {
        public int admin_level_id { get; set; }
        public int Htag1 { get; set; }
        public int Tag1 { get; set; }
        public string Topic1 { get; set; }
        public Nullable<int> Active1 { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
    }
}
