//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkAPI_Parking
    {
        public int API_ID { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string CardPrefix { get; set; }
        public Nullable<int> Require_Token { get; set; }
        public Nullable<int> fn_api_id { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
