//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkCardHist
    {
        public int CardHist_ID { get; set; }
        public string Scr_No { get; set; }
        public string CscMain_ID { get; set; }
        public string Rabbit_ID { get; set; }
        public string CustNo { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Tenant { get; set; }
        public string CardType { get; set; }
        public string Status { get; set; }
        public string CarId { get; set; }
        public string CarModel { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Earnest { get; set; }
        public string ReceiptCode { get; set; }
        public Nullable<decimal> PayFirstMonth { get; set; }
        public Nullable<decimal> Paymonth { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public Nullable<System.DateTime> FirstIssueDate { get; set; }
        public string CM_DocNo { get; set; }
        public string LastCSCMain_ID { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
    }
}
