//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkCardType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PkCardType()
        {
            this.PkFaremedia_Cardtype = new HashSet<PkFaremedia_Cardtype>();
        }
    
        public int CardType_Id { get; set; }
        public string Zdesc { get; set; }
        public Nullable<int> cashpay { get; set; }
        public string cartype { get; set; }
        public Nullable<int> Overnightflg { get; set; }
        public Nullable<System.TimeSpan> Timein1 { get; set; }
        public Nullable<System.TimeSpan> Timein2 { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
        public Nullable<int> Active1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PkFaremedia_Cardtype> PkFaremedia_Cardtype { get; set; }
    }
}
