//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkcar_motor_ofcompanyovernight
    {
        public string CustNo { get; set; }
        public System.DateTime Dateparking { get; set; }
        public string CarType { get; set; }
        public string terncode { get; set; }
        public string ternname { get; set; }
        public string Name { get; set; }
        public string Scr_No { get; set; }
        public string CscMain_ID { get; set; }
        public Nullable<System.DateTime> Indate { get; set; }
        public Nullable<int> Typecard { get; set; }
        public Nullable<System.DateTime> DateIn1 { get; set; }
        public Nullable<System.TimeSpan> TimeIn1 { get; set; }
        public string CarID { get; set; }
        public Nullable<decimal> Cash { get; set; }
    }
}
