//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkDepartment
    {
        public int DeptIDAuto { get; set; }
        public string CompanyID { get; set; }
        public string Terncode { get; set; }
        public string DeptID { get; set; }
        public string DeptName { get; set; }
        public string Zdesc { get; set; }
        public string SupDepID { get; set; }
        public Nullable<int> Level1 { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public string Memo { get; set; }
        public string No1 { get; set; }
        public string Building { get; set; }
        public string Room { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string Street { get; set; }
        public string Subdistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Zipcode { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Floor { get; set; }
        public string TaxID { get; set; }
        public Nullable<int> Loc_ID { get; set; }
        public Nullable<int> TypeCompany { get; set; }
        public string Typebill { get; set; }
        public string Groupbill { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> GDoorID { get; set; }
        public Nullable<int> sf { get; set; }
        public string inizdesc { get; set; }
        public string Fullname { get; set; }
        public Nullable<int> Loc_allowparking { get; set; }
        public Nullable<int> Loc_allowparkingzone { get; set; }
        public Nullable<int> Cancel1 { get; set; }
        public Nullable<System.DateTime> Canceldate { get; set; }
        public Nullable<int> Calcarcompany { get; set; }
        public Nullable<int> CarcompanyLimit { get; set; }
        public Nullable<decimal> Paycarcompanyoverlimit { get; set; }
        public Nullable<int> Calmotorcompany { get; set; }
        public Nullable<int> MotorcompanyLimit { get; set; }
        public Nullable<decimal> Paymotorcompanyoverlimit { get; set; }
    }
}
