//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkemailtenant
    {
        public string EmailAddress { get; set; }
        public string SMTPServer { get; set; }
        public string Portdefault { get; set; }
        public string Smtpid { get; set; }
        public string smtppassword { get; set; }
        public string Name { get; set; }
        public string Telephoneno { get; set; }
        public string Mobileno { get; set; }
        public string Terncode { get; set; }
        public string Ternsubcode { get; set; }
        public Nullable<int> Isactive { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public string Updateby { get; set; }
    }
}
