//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkEquip
    {
        public int Equip_ID { get; set; }
        public string Site_ID { get; set; }
        public int Loc_ID { get; set; }
        public string Zdesc { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<int> status { get; set; }
        public string Ipaddress { get; set; }
        public string Servername { get; set; }
        public string username { get; set; }
        public string password1 { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<int> booth1 { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
        public string PosId { get; set; }
        public string Cartype { get; set; }
    }
}
