//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkgroupbill
    {
        public string GroupMember { get; set; }
        public string Terncode { get; set; }
        public string Name1 { get; set; }
        public string No1 { get; set; }
        public string Building { get; set; }
        public string Room { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string Street { get; set; }
        public string Subdistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Zipcode { get; set; }
        public string TaxID { get; set; }
        public string Typebill { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
    }
}
