//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkGroupaccess
    {
        public int GroupID { get; set; }
        public string Groupaccess { get; set; }
        public string Zdesc { get; set; }
        public string Defaultfloor { get; set; }
        public string Grouptypes { get; set; }
        public Nullable<int> vflag { get; set; }
    }
}
