//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkHolidayD
    {
        public string HolCode { get; set; }
        public string ItemCode { get; set; }
        public System.DateTime ZDate { get; set; }
        public string ZDesc { get; set; }
        public Nullable<System.DateTime> Last_upd { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
    
        public virtual PkHoliday PkHoliday { get; set; }
    }
}
