//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKINVOICETemp
    {
        public string INV_ID { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<System.DateTime> INV_date { get; set; }
        public string CarID { get; set; }
        public string VCID { get; set; }
        public string InOutTran_ID { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public string Bywhom { get; set; }
        public string Zuser { get; set; }
        public Nullable<decimal> Sumtotal { get; set; }
        public Nullable<decimal> Lost_card_fine { get; set; }
        public Nullable<int> sumno { get; set; }
        public Nullable<System.DateTime> printdate { get; set; }
        public Nullable<decimal> OvernightFine { get; set; }
        public Nullable<int> Gateid { get; set; }
        public string companyname { get; set; }
        public string adr1 { get; set; }
        public string adr2 { get; set; }
        public string posid { get; set; }
        public string Taxid { get; set; }
        public string Tel1 { get; set; }
        public string Branch { get; set; }
        public string Buildingname { get; set; }
    }
}
