//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkLocation
    {
        public int Loc_ID { get; set; }
        public int Site_ID { get; set; }
        public string ZDesc { get; set; }
        public string Addr1 { get; set; }
        public Nullable<int> Spaceparking { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<int> sf { get; set; }
        public Nullable<System.DateTime> Syndate { get; set; }
        public string Timein_car { get; set; }
        public string Timeout_car { get; set; }
        public string Timein_Motor { get; set; }
        public string Timeout_Motor { get; set; }
        public Nullable<int> Exceptin_Car { get; set; }
        public string Excepttimein_Car { get; set; }
        public Nullable<int> Exceptin_Motor { get; set; }
        public string Excepttimein_Motor { get; set; }
    
        public virtual Pksite Pksite { get; set; }
    }
}
