//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PklogIO_Notworking
    {
        public int Id { get; set; }
        public string IO_IP { get; set; }
        public string Inouttran_Id { get; set; }
        public string Car_Id { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> GateId { get; set; }
    }
}
