//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pklocationparkingzone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pklocationparkingzone()
        {
            this.Pklocationparkingzonedes = new HashSet<Pklocationparkingzonede>();
        }
    
        public int Zoneid1 { get; set; }
        public Nullable<int> Site_ID { get; set; }
        public string zDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pklocationparkingzonede> Pklocationparkingzonedes { get; set; }
    }
}
