//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkmonthlychangedata
    {
        public int Month1 { get; set; }
        public int Year1 { get; set; }
        public int Period1 { get; set; }
        public string cartype { get; set; }
        public string Cscmain_id { get; set; }
        public Nullable<System.DateTime> Issuedate { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TernCode { get; set; }
        public string TernSubCode { get; set; }
        public string ternname { get; set; }
        public string Scr_no { get; set; }
        public string Name { get; set; }
        public Nullable<int> Overnighttimes { get; set; }
        public Nullable<decimal> Overnightfee { get; set; }
        public Nullable<int> Lostcardtimes { get; set; }
        public Nullable<decimal> LostCardfine { get; set; }
        public Nullable<int> Changedatatimes { get; set; }
        public Nullable<decimal> Changedatafee { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Taxwithholding { get; set; }
        public Nullable<decimal> MonthlyFeeVat { get; set; }
        public Nullable<decimal> Monthlywithholding { get; set; }
        public Nullable<decimal> NetFee { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Typecompany { get; set; }
        public Nullable<int> OvernighttimesBill { get; set; }
        public Nullable<decimal> OvernightfeeBill { get; set; }
        public Nullable<int> LostcardtimesBill { get; set; }
        public Nullable<decimal> LostCardfineBill { get; set; }
        public Nullable<int> ChangedatatimesBill { get; set; }
        public Nullable<decimal> ChangedatafeeBill { get; set; }
    }
}
