//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkmonthlyperiod
    {
        public int Month1 { get; set; }
        public int Year1 { get; set; }
        public int Period1 { get; set; }
        public string cartype { get; set; }
        public string Cscmain_id { get; set; }
        public Nullable<System.DateTime> Issuedate { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TernCode { get; set; }
        public string TernSubCode { get; set; }
        public string ternname { get; set; }
        public string Scr_no { get; set; }
        public string Name { get; set; }
        public string CarID { get; set; }
        public string CarModel { get; set; }
        public string CarID1 { get; set; }
        public string CarModel1 { get; set; }
        public string CarID2 { get; set; }
        public string CarModel2 { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> FirstUse { get; set; }
        public Nullable<decimal> MonthlyFee { get; set; }
        public Nullable<decimal> MonthlyFeeVat { get; set; }
        public Nullable<decimal> Monthlywithholding { get; set; }
        public Nullable<decimal> NetFee { get; set; }
        public Nullable<decimal> MonthlyFee_Cash { get; set; }
        public string Memo { get; set; }
        public string typecontact { get; set; }
        public Nullable<int> Typecontactsub { get; set; }
        public string Pay { get; set; }
        public string Statuspay { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public Nullable<int> Typecompany { get; set; }
        public string Group1 { get; set; }
        public string Address1 { get; set; }
        public Nullable<System.DateTime> Datepay { get; set; }
        public string rabbit_id { get; set; }
        public Nullable<decimal> Overnightfee { get; set; }
        public string Overnightfee_note { get; set; }
        public Nullable<decimal> LostCardfine { get; set; }
        public Nullable<decimal> Changedatafee { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Taxwithholding { get; set; }
        public string Cscmain_id1 { get; set; }
        public string Cscmain_id2 { get; set; }
        public string Cscmain_id3 { get; set; }
    }
}
