//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkNegativeCard
    {
        public int NegativeCard_ID { get; set; }
        public string CustNo { get; set; }
        public string Scr_No { get; set; }
        public string CscMain_ID { get; set; }
        public string Rabbit_ID { get; set; }
        public string Neg_IN { get; set; }
        public string Neg_Out { get; set; }
        public string Pass { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
    }
}
