//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkopengateemergency
    {
        public int No1 { get; set; }
        public Nullable<System.DateTime> Datetimeopen { get; set; }
        public Nullable<int> Gateid { get; set; }
        public string GateName { get; set; }
        public string Zuser { get; set; }
        public string Memo1 { get; set; }
    }
}
