//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKParkingShift
    {
        public int ID { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public Nullable<int> Equip_ID { get; set; }
        public Nullable<System.DateTime> SHdateIN { get; set; }
        public Nullable<System.DateTime> SHDateOUT { get; set; }
        public Nullable<int> totalCar { get; set; }
        public Nullable<int> totalTrans { get; set; }
        public Nullable<int> TotalSlip { get; set; }
        public Nullable<int> TotalLoss { get; set; }
        public Nullable<int> TotalSUM { get; set; }
        public Nullable<int> completeFlag { get; set; }
        public string SH_ID { get; set; }
        public Nullable<int> OvernightFine { get; set; }
        public string Username { get; set; }
        public Nullable<int> itemno { get; set; }
    }
}
