//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkrequirechangemember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pkrequirechangemember()
        {
            this.Pkrequirechangememberdocs = new HashSet<Pkrequirechangememberdoc>();
        }
    
        public string No1 { get; set; }
        public Nullable<System.DateTime> dateissue { get; set; }
        public string terncode { get; set; }
        public Nullable<int> Statustype { get; set; }
        public string Custno { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string MemberType { get; set; }
        public Nullable<int> Changecontacttype { get; set; }
        public Nullable<int> Contacttype_New { get; set; }
        public Nullable<int> Contacttype_Old { get; set; }
        public Nullable<int> Paytype { get; set; }
        public Nullable<int> Changecarid { get; set; }
        public string CarID_New { get; set; }
        public string CarModel_New { get; set; }
        public string Carcolor_New { get; set; }
        public string CarID1_New { get; set; }
        public string CarModel1_New { get; set; }
        public string Carcolor1_New { get; set; }
        public string CarID2_New { get; set; }
        public string CarModel2_New { get; set; }
        public string Carcolor2_New { get; set; }
        public string CarID_Old { get; set; }
        public string CarModel_Old { get; set; }
        public string Carcolor_Old { get; set; }
        public string CarID2_Old { get; set; }
        public string CarModel2_Old { get; set; }
        public string Carcolor2_Old { get; set; }
        public string CarID3_Old { get; set; }
        public string CarModel3_Old { get; set; }
        public string Carcolor3_Old { get; set; }
        public Nullable<System.DateTime> Dateactive { get; set; }
        public Nullable<int> Clearflag { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public string Updateby { get; set; }
        public string Ssn { get; set; }
        public string Mobile { get; set; }
        public string Emailaddress { get; set; }
        public string Remark { get; set; }
        public string Approveby { get; set; }
        public Nullable<System.DateTime> Approvedate { get; set; }
        public string Approveresult { get; set; }
        public string Efname { get; set; }
        public string Elname { get; set; }
        public Nullable<int> usetype { get; set; }
        public string SlifeID { get; set; }
        public string Telephone { get; set; }
        public string Fname_New { get; set; }
        public string Lname_New { get; set; }
        public string Changename { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pkrequirechangememberdoc> Pkrequirechangememberdocs { get; set; }
    }
}
