//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkrequirechangememberdoc
    {
        public string No1 { get; set; }
        public string Documentype { get; set; }
        public byte[] Documentimage { get; set; }
        public string pathFile { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public string Updateby { get; set; }
        public string filename { get; set; }
    
        public virtual Pkrequirechangemember Pkrequirechangemember { get; set; }
    }
}
