//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pksite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pksite()
        {
            this.PkLocations = new HashSet<PkLocation>();
        }
    
        public int Site_ID { get; set; }
        public string ZDesc { get; set; }
        public string ZDesc_eng { get; set; }
        public string TaxID { get; set; }
        public string Addr1 { get; set; }
        public string ZipCode { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<int> TaxFlg { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<decimal> withholdingtax { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<int> Spaceparking { get; set; }
        public string DateMonthFare { get; set; }
        public string DateHalfMonthFare { get; set; }
        public Nullable<decimal> Issuecard_fee { get; set; }
        public Nullable<decimal> Issuecard_motor_fee { get; set; }
        public Nullable<decimal> deposit_fee { get; set; }
        public Nullable<decimal> deposit_motor_fee { get; set; }
        public string precis1 { get; set; }
        public Nullable<decimal> Issuecard_deposit { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
        public string adr1 { get; set; }
        public string adr2 { get; set; }
        public Nullable<int> Typecalculate { get; set; }
        public Nullable<int> singlestamptype { get; set; }
        public Nullable<int> Maxcardmember_car { get; set; }
        public Nullable<int> Maxcardmember_motor { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> Changedata_Fee { get; set; }
        public Nullable<decimal> Changedata_motor_Fee { get; set; }
        public Nullable<int> Stampdefine { get; set; }
        public string Buildingname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PkLocation> PkLocations { get; set; }
    }
}
