//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkstamptemplate
    {
        public string StampCode { get; set; }
        public string Stampno { get; set; }
        public string Cartype { get; set; }
        public string StampAbbr { get; set; }
        public string ZDesc { get; set; }
        public string Flg { get; set; }
        public string TernCode { get; set; }
        public string TernSubCode { get; set; }
        public string PayMonthFlg { get; set; }
        public Nullable<int> CoverDay { get; set; }
        public Nullable<System.DateTime> CoverTime { get; set; }
        public string EventAccept { get; set; }
        public string EventCode { get; set; }
        public string TernEventPrice { get; set; }
        public string CustEventPrice { get; set; }
        public string HolAccept { get; set; }
        public string HolCode { get; set; }
        public string TernHolPrice { get; set; }
        public string CustHolPrice { get; set; }
        public string WeekAccept { get; set; }
        public string WeekCode { get; set; }
        public string TernWeekPrice { get; set; }
        public string CustWeekPrice { get; set; }
        public string NormalAccept { get; set; }
        public string TernNormalPrice { get; set; }
        public string CustNormalPrice { get; set; }
        public string OnePriceFlag { get; set; }
        public Nullable<decimal> OnePriceTern { get; set; }
        public Nullable<decimal> OnePriceCust { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<int> SingleStampFlg { get; set; }
        public Nullable<int> admin_level_id { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
        public string ExceptAccept { get; set; }
        public string ExceptCode { get; set; }
        public string TernExceptPrice { get; set; }
        public string CustExceptPrice { get; set; }
        public Nullable<decimal> OnepriceOverTern { get; set; }
        public Nullable<decimal> OnepriceOverCust { get; set; }
        public Nullable<int> PaymonthOvertypeTern { get; set; }
        public Nullable<int> PaymonthOvertypeCust { get; set; }
        public Nullable<int> Costamp { get; set; }
        public string Costampcode { get; set; }
        public Nullable<int> Costampupto { get; set; }
        public string Costampcodereplace { get; set; }
        public Nullable<int> CostamphourFee { get; set; }
        public Nullable<int> CostamptypeTern { get; set; }
        public Nullable<int> CostamptypeCust { get; set; }
        public Nullable<decimal> CostamppriceTern { get; set; }
        public Nullable<decimal> CostamppriceCust { get; set; }
        public Nullable<int> Exceptovernightfine { get; set; }
        public Nullable<int> CalHourType { get; set; }
        public Nullable<int> exceptcalfreeday { get; set; }
    }
}
