//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pksummaryincome_bymonth
    {
        public int Month1 { get; set; }
        public int year1 { get; set; }
        public int period1 { get; set; }
        public string Terncode { get; set; }
        public int No1 { get; set; }
        public string Cartype { get; set; }
        public int typereport1 { get; set; }
        public string Companyname { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Typecal { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Code1 { get; set; }
        public string List1 { get; set; }
        public Nullable<int> Right1 { get; set; }
        public Nullable<int> Billcar { get; set; }
        public Nullable<decimal> Billamount { get; set; }
        public Nullable<int> Cashcar { get; set; }
        public Nullable<decimal> Cashamount { get; set; }
        public Nullable<int> totalcar { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public string Note { get; set; }
    }
}
