//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pkterminalstamp
    {
        public int Terminal_ID { get; set; }
        public string terncode { get; set; }
        public Nullable<int> LastActive { get; set; }
        public Nullable<int> Status { get; set; }
        public string adminname { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> sf { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c4 { get; set; }
        public string c5 { get; set; }
        public string m1 { get; set; }
        public string m2 { get; set; }
        public string m3 { get; set; }
        public string m4 { get; set; }
        public string m5 { get; set; }
    }
}
