//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkTimetable
    {
        public string Tabletype { get; set; }
        public string Tablecode { get; set; }
        public string Tabledesc { get; set; }
        public string Flag { get; set; }
        public Nullable<double> H00_15 { get; set; }
        public Nullable<double> H00_30 { get; set; }
        public Nullable<double> H00_45 { get; set; }
        public Nullable<double> H00_60 { get; set; }
        public Nullable<double> H01_15 { get; set; }
        public Nullable<double> H01_30 { get; set; }
        public Nullable<double> H01_45 { get; set; }
        public Nullable<double> H01_60 { get; set; }
        public Nullable<double> H02_15 { get; set; }
        public Nullable<double> H02_30 { get; set; }
        public Nullable<double> H02_45 { get; set; }
        public Nullable<double> H02_60 { get; set; }
        public Nullable<double> H03_15 { get; set; }
        public Nullable<double> H03_30 { get; set; }
        public Nullable<double> H03_45 { get; set; }
        public Nullable<double> H03_60 { get; set; }
        public Nullable<double> H04_15 { get; set; }
        public Nullable<double> H04_30 { get; set; }
        public Nullable<double> H04_45 { get; set; }
        public Nullable<double> H04_60 { get; set; }
        public Nullable<double> H05_15 { get; set; }
        public Nullable<double> H05_30 { get; set; }
        public Nullable<double> H05_45 { get; set; }
        public Nullable<double> H05_60 { get; set; }
        public Nullable<double> H06_15 { get; set; }
        public Nullable<double> H06_30 { get; set; }
        public Nullable<double> H06_45 { get; set; }
        public Nullable<double> H06_60 { get; set; }
        public Nullable<double> H07_15 { get; set; }
        public Nullable<double> H07_30 { get; set; }
        public Nullable<double> H07_45 { get; set; }
        public Nullable<double> H07_60 { get; set; }
        public Nullable<double> H08_15 { get; set; }
        public Nullable<double> H08_30 { get; set; }
        public Nullable<double> H08_45 { get; set; }
        public Nullable<double> H08_60 { get; set; }
        public Nullable<double> H09_15 { get; set; }
        public Nullable<double> H09_30 { get; set; }
        public Nullable<double> H09_45 { get; set; }
        public Nullable<double> H09_60 { get; set; }
        public Nullable<double> H10_15 { get; set; }
        public Nullable<double> H10_30 { get; set; }
        public Nullable<double> H10_45 { get; set; }
        public Nullable<double> H10_60 { get; set; }
        public Nullable<double> H11_15 { get; set; }
        public Nullable<double> H11_30 { get; set; }
        public Nullable<double> H11_45 { get; set; }
        public Nullable<double> H11_60 { get; set; }
        public Nullable<double> H12_15 { get; set; }
        public Nullable<double> H12_30 { get; set; }
        public Nullable<double> H12_45 { get; set; }
        public Nullable<double> H12_60 { get; set; }
        public Nullable<double> H13_15 { get; set; }
        public Nullable<double> H13_30 { get; set; }
        public Nullable<double> H13_45 { get; set; }
        public Nullable<double> H13_60 { get; set; }
        public Nullable<double> H14_15 { get; set; }
        public Nullable<double> H14_30 { get; set; }
        public Nullable<double> H14_45 { get; set; }
        public Nullable<double> H14_60 { get; set; }
        public Nullable<double> H15_15 { get; set; }
        public Nullable<double> H15_30 { get; set; }
        public Nullable<double> H15_45 { get; set; }
        public Nullable<double> H15_60 { get; set; }
        public Nullable<double> H16_15 { get; set; }
        public Nullable<double> H16_30 { get; set; }
        public Nullable<double> H16_45 { get; set; }
        public Nullable<double> H16_60 { get; set; }
        public Nullable<double> H17_15 { get; set; }
        public Nullable<double> H17_30 { get; set; }
        public Nullable<double> H17_45 { get; set; }
        public Nullable<double> H17_60 { get; set; }
        public Nullable<double> H18_15 { get; set; }
        public Nullable<double> H18_30 { get; set; }
        public Nullable<double> H18_45 { get; set; }
        public Nullable<double> H18_60 { get; set; }
        public Nullable<double> H19_15 { get; set; }
        public Nullable<double> H19_30 { get; set; }
        public Nullable<double> H19_45 { get; set; }
        public Nullable<double> H19_60 { get; set; }
        public Nullable<double> H20_15 { get; set; }
        public Nullable<double> H20_30 { get; set; }
        public Nullable<double> H20_45 { get; set; }
        public Nullable<double> H20_60 { get; set; }
        public Nullable<double> H21_15 { get; set; }
        public Nullable<double> H21_30 { get; set; }
        public Nullable<double> H21_45 { get; set; }
        public Nullable<double> H21_60 { get; set; }
        public Nullable<double> H22_15 { get; set; }
        public Nullable<double> H22_30 { get; set; }
        public Nullable<double> H22_45 { get; set; }
        public Nullable<double> H22_60 { get; set; }
        public Nullable<double> H23_15 { get; set; }
        public Nullable<double> H23_30 { get; set; }
        public Nullable<double> H23_45 { get; set; }
        public Nullable<double> H23_60 { get; set; }
        public string PriceTableCode1 { get; set; }
        public string PriceTableCode2 { get; set; }
        public string PriceTableCode3 { get; set; }
        public string PriceTableCode4 { get; set; }
        public string PriceTableCode5 { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
        public Nullable<double> H24over { get; set; }
    }
}
