//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QR_Push_VUID
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public string Username { get; set; }
        public string Command { get; set; }
        public string Device_ID { get; set; }
        public string VUID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> Clear { get; set; }
        public string Card_ID { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Template { get; set; }
        public string Location { get; set; }
        public string Access_id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public string User_ID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<System.DateTime> Duration_expire { get; set; }
        public string Vcardid { get; set; }
        public string Ncardid { get; set; }
    }
}
