//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QR_rq_log
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public string Username { get; set; }
        public string Command { get; set; }
        public string s_Life_Id { get; set; }
        public string mobile { get; set; }
        public string Replycom { get; set; }
        public string Apprequest { get; set; }
        public string DefaultFloor { get; set; }
        public string Qrem { get; set; }
        public string Flag { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> Clear { get; set; }
        public string Card_ID { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Template { get; set; }
        public string Location { get; set; }
        public string Access_ID { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> activedate { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public string User_ID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<System.DateTime> Duration_Expire { get; set; }
    }
}
