//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealTimeLog
    {
        public int ID { get; set; }
        public Nullable<int> WorkTimeID { get; set; }
        public Nullable<int> RealTimeID { get; set; }
        public Nullable<byte> OldTFlag { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<byte> NewTFlag { get; set; }
        public Nullable<System.DateTime> NewDate { get; set; }
        public string FillTo { get; set; }
        public Nullable<int> edituserid { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
