//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealTime
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> userid { get; set; }
        public string Badgenumber { get; set; }
        public Nullable<int> Fkey { get; set; }
        public Nullable<int> tid { get; set; }
        public Nullable<int> door { get; set; }
        public Nullable<byte> tflag { get; set; }
        public bool NoFill { get; set; }
    }
}
