//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHCLASSMINI
    {
        public int SCHCLASSID { get; set; }
        public string SCHNAME { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<int> LATEMINUTES { get; set; }
        public Nullable<int> EARLYMINUTES { get; set; }
        public Nullable<int> CHECKIN { get; set; }
        public Nullable<int> CHECKOUT { get; set; }
        public Nullable<System.DateTime> CHECKINTIME1 { get; set; }
        public Nullable<System.DateTime> CHECKINTIME2 { get; set; }
        public Nullable<System.DateTime> CHECKOUTTIME1 { get; set; }
        public Nullable<System.DateTime> CHECKOUTTIME2 { get; set; }
        public Nullable<int> COLOR { get; set; }
        public Nullable<int> AUTOBIND { get; set; }
        public Nullable<double> WorkDay { get; set; }
        public string SensorID { get; set; }
        public string Sun1 { get; set; }
        public string Mon1 { get; set; }
        public string Tue1 { get; set; }
        public string Wed1 { get; set; }
        public string Thu1 { get; set; }
        public string Fri1 { get; set; }
        public string Sat1 { get; set; }
        public Nullable<System.DateTime> OverIn { get; set; }
        public Nullable<System.DateTime> Over_Out { get; set; }
        public Nullable<System.DateTime> CBreakMiniOvertime { get; set; }
        public Nullable<System.DateTime> MiniOvertime { get; set; }
        public Nullable<System.DateTime> Noworkfrom1 { get; set; }
        public Nullable<System.DateTime> Noworkto1 { get; set; }
        public Nullable<System.DateTime> Noworkfrom2 { get; set; }
        public Nullable<System.DateTime> Noworkto2 { get; set; }
        public Nullable<int> OT { get; set; }
    }
}
