//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCode
    {
        public int ID { get; set; }
        public Nullable<int> siteID { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> BL1 { get; set; }
        public Nullable<int> BL2 { get; set; }
        public string TL1 { get; set; }
        public Nullable<int> LEVEL { get; set; }
    }
}
