//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_device
    {
        public int nIndex { get; set; }
        public string strName { get; set; }
        public Nullable<int> nDeviceType { get; set; }
        public Nullable<int> nDeviceID { get; set; }
        public string strComPort { get; set; }
        public string strBaudrate { get; set; }
        public Nullable<int> nIPAddr { get; set; }
        public Nullable<int> nIPPort { get; set; }
        public Nullable<int> nCommType { get; set; }
        public Nullable<int> nProtocol { get; set; }
        public Nullable<int> bHasParent { get; set; }
        public Nullable<int> nReader1ID { get; set; }
        public Nullable<int> nReader2ID { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<int> bDefaultDevice { get; set; }
    }
}
