//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_doorzone
    {
        public int nIndex { get; set; }
        public string strName { get; set; }
        public Nullable<int> bActive { get; set; }
        public Nullable<int> ServerPort { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public Nullable<int> Custom1N { get; set; }
        public Nullable<int> Custom2N { get; set; }
        public string ServerIP { get; set; }
        public Nullable<int> Custom3N { get; set; }
        public Nullable<int> Custom4N { get; set; }
        public Nullable<int> Custom5N { get; set; }
    }
}
