//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Door
    {
        public Nullable<int> ID { get; set; }
        public int MTID { get; set; }
        public Nullable<int> STID { get; set; }
        public Nullable<int> MID { get; set; }
        public int Door { get; set; }
        public string Location { get; set; }
        public int DoorID { get; set; }
        public Nullable<int> DoorOpentime { get; set; }
        public Nullable<int> LockReltime { get; set; }
        public Nullable<int> CardPinTZ { get; set; }
        public Nullable<int> LockRelTZ { get; set; }
        public Nullable<int> pushTZ { get; set; }
        public Nullable<int> FPPINTz { get; set; }
        public Nullable<int> AntiPBOut { get; set; }
        public Nullable<int> AntiPBIN { get; set; }
        public Nullable<int> RelayTrigger { get; set; }
        public Nullable<int> DoorType { get; set; }
        public Nullable<int> ReaderType { get; set; }
        public Nullable<int> Resv { get; set; }
        public Nullable<int> Handel { get; set; }
        public string Misc { get; set; }
        public Nullable<int> doorx { get; set; }
        public Nullable<int> doory { get; set; }
        public Nullable<int> doorz { get; set; }
        public Nullable<int> zone { get; set; }
        public Nullable<int> sitecode { get; set; }
        public Nullable<int> doorref { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> show { get; set; }
        public Nullable<int> alarm { get; set; }
        public Nullable<int> mode { get; set; }
        public Nullable<int> alert { get; set; }
        public Nullable<int> group { get; set; }
        public string groups { get; set; }
        public Nullable<int> Doublebagetz { get; set; }
        public Nullable<int> accesslog { get; set; }
        public Nullable<int> Doubleapply { get; set; }
        public Nullable<int> installat { get; set; }
        public Nullable<int> ReaderTYPEoUT { get; set; }
        public Nullable<int> ADR { get; set; }
        public Nullable<int> ADRPW { get; set; }
        public Nullable<int> DDInterlock { get; set; }
        public Nullable<int> APBenable { get; set; }
        public Nullable<int> APBtime { get; set; }
    }
}
