//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_titlecode
    {
        public int nIndex { get; set; }
        public int Titleid { get; set; }
        public string strName { get; set; }
        public string StrNameT { get; set; }
    }
}
