//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateFingerVein
    {
        public int TEMPLATEID { get; set; }
        public string USERID { get; set; }
        public byte[] FVPattern1 { get; set; }
        public byte[] FVPattern2 { get; set; }
    }
}
