//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateFace
    {
        public int TEMPLATEID { get; set; }
        public string USERID { get; set; }
        public byte[] FaceTemp1 { get; set; }
        public byte[] FaceTemp2 { get; set; }
        public byte[] FaceTemp3 { get; set; }
        public byte[] FaceTemp4 { get; set; }
        public byte[] FaceTemp5 { get; set; }
        public byte[] FaceTemp6 { get; set; }
        public byte[] FaceTemp7 { get; set; }
        public byte[] FaceTemp8 { get; set; }
        public byte[] FaceTemp9 { get; set; }
        public byte[] FaceTemp10 { get; set; }
        public byte[] FaceTemp11 { get; set; }
        public byte[] FaceTemp12 { get; set; }
        public byte[] FaceTemp13 { get; set; }
        public byte[] FaceTemp14 { get; set; }
        public byte[] FaceTemp15 { get; set; }
        public byte[] FaceTemp16 { get; set; }
        public byte[] FaceTemp17 { get; set; }
        public byte[] FaceTemp18 { get; set; }
        public byte[] FaceTemp { get; set; }
    }
}
