//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSet
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> StartH { get; set; }
        public Nullable<int> StartM { get; set; }
        public Nullable<int> EndH { get; set; }
        public Nullable<int> EndM { get; set; }
        public Nullable<int> active { get; set; }
    }
}
