//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeGroup
    {
        public int GID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> GNO { get; set; }
        public Nullable<int> timezoneID { get; set; }
        public string name { get; set; }
        public Nullable<int> accessMain { get; set; }
        public Nullable<int> acessdoor1 { get; set; }
        public Nullable<int> acessdoor2 { get; set; }
        public Nullable<int> acessdoor3 { get; set; }
        public Nullable<int> acessdoor4 { get; set; }
        public Nullable<int> acessdoor5 { get; set; }
        public Nullable<int> acessdoor6 { get; set; }
        public Nullable<int> acessdoor7 { get; set; }
        public Nullable<int> accessdoor8 { get; set; }
        public string misc { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> LiftFlag { get; set; }
        public string LiftFloor { get; set; }
        public Nullable<int> LiftFlag1 { get; set; }
        public Nullable<int> LiftFlag2 { get; set; }
        public Nullable<int> LiftFlag3 { get; set; }
        public Nullable<int> LiftFlag4 { get; set; }
        public Nullable<int> LiftFlag5 { get; set; }
        public Nullable<int> LiftFlag6 { get; set; }
        public Nullable<int> LiftFlag7 { get; set; }
        public Nullable<int> LiftFlag8 { get; set; }
    }
}
