//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> C1time1 { get; set; }
        public Nullable<int> C1time2 { get; set; }
        public Nullable<int> C1time3 { get; set; }
        public Nullable<int> C2time1 { get; set; }
        public Nullable<int> C2time2 { get; set; }
        public Nullable<int> C2time3 { get; set; }
        public Nullable<int> C3time1 { get; set; }
        public Nullable<int> C3time2 { get; set; }
        public Nullable<int> C3time3 { get; set; }
        public Nullable<int> C4time1 { get; set; }
        public Nullable<int> C4time2 { get; set; }
        public Nullable<int> C4time3 { get; set; }
        public Nullable<int> C5time1 { get; set; }
        public Nullable<int> C5time2 { get; set; }
        public Nullable<int> C5time3 { get; set; }
        public Nullable<int> C6time1 { get; set; }
        public Nullable<int> C6time2 { get; set; }
        public Nullable<int> C6time3 { get; set; }
        public Nullable<int> C7time1 { get; set; }
        public Nullable<int> C7time2 { get; set; }
        public Nullable<int> C7time3 { get; set; }
        public Nullable<int> C8time1 { get; set; }
        public Nullable<int> C8time2 { get; set; }
        public Nullable<int> C8time3 { get; set; }
        public Nullable<int> active { get; set; }
    }
}
