//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeGDoorD
    {
        public int GdoorID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public int GID { get; set; }
        public int TID { get; set; }
        public Nullable<int> Gno { get; set; }
        public Nullable<int> TimezoneID { get; set; }
        public Nullable<int> active { get; set; }
        public string Misc { get; set; }
    }
}
