//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmail
    {
        public int EmailID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string BadgeNumber { get; set; }
        public Nullable<int> UserIndex { get; set; }
        public string SMTPServer { get; set; }
        public string EmailUserID { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public string AdminID { get; set; }
        public string Username { get; set; }
        public string EmailAddress { get; set; }
    }
}
