//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SPEDAY
    {
        public string USERID { get; set; }
        public string Badgenumber { get; set; }
        public System.DateTime STARTSPECDAY { get; set; }
        public Nullable<System.DateTime> ENDSPECDAY { get; set; }
        public int DATEID { get; set; }
        public string YUANYING { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
