//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBilling_memberfee
    {
        public string CustNo { get; set; }
        public string InOutTran_ID { get; set; }
        public Nullable<System.DateTime> Indate { get; set; }
        public Nullable<System.DateTime> Outdate { get; set; }
        public Nullable<System.DateTime> DateIn1 { get; set; }
        public Nullable<System.DateTime> DateOut1 { get; set; }
        public string CscMain_ID { get; set; }
        public Nullable<int> Typecard { get; set; }
        public string INV_ID { get; set; }
        public Nullable<decimal> SumTotal { get; set; }
        public Nullable<decimal> Lost_Card_Fine { get; set; }
        public Nullable<decimal> Overnightpark_Fine { get; set; }
        public Nullable<decimal> Totalamount { get; set; }
        public Nullable<int> cashpay { get; set; }
        public string cartype { get; set; }
        public string terncode { get; set; }
        public string zdesc { get; set; }
    }
}
