//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCadmin
    {
        public int ID1 { get; set; }
        public string Username1 { get; set; }
        public string Password1 { get; set; }
        public string Level1 { get; set; }
        public string Memo1 { get; set; }
        public string Name1 { get; set; }
        public string Typeadmin { get; set; }
    }
}
