//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCadminlog
    {
        public int ID1 { get; set; }
        public string Name1 { get; set; }
        public Nullable<int> Tag1 { get; set; }
        public string Thaipanel { get; set; }
        public string EngPanel { get; set; }
        public string Add { get; set; }
        public string Edit { get; set; }
        public string Delete { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> Datetime1 { get; set; }
    }
}
