//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCard
    {
        public int VisitorCardindex { get; set; }
        public string VistorCardID { get; set; }
        public string VCardNo { get; set; }
        public string VCardNos { get; set; }
        public string Floor { get; set; }
        public string Box { get; set; }
        public string Door { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> Clearing { get; set; }
        public string memo1 { get; set; }
        public string timeset { get; set; }
        public string CardType { get; set; }
        public Nullable<System.DateTime> Expiredate { get; set; }
        public string MemID { get; set; }
        public Nullable<int> MemNo { get; set; }
        public string MemName { get; set; }
        public string MemPhone { get; set; }
        public string MemAddress { get; set; }
        public string MemTime { get; set; }
        public string MemMemo { get; set; }
        public string SubID { get; set; }
        public Nullable<int> SubNo { get; set; }
        public string SubName { get; set; }
        public string SubAddress { get; set; }
        public string SiubPhone { get; set; }
        public string SubTime { get; set; }
        public string SunMemo { get; set; }
        public string WorkID { get; set; }
        public Nullable<int> WorkNo { get; set; }
        public string WorkName { get; set; }
        public string WorkAddress { get; set; }
        public string WorkPhone { get; set; }
        public string WorkTime { get; set; }
        public string WorkMemo { get; set; }
        public Nullable<System.DateTime> datelostcard { get; set; }
        public Nullable<System.DateTime> dateClearlostcard { get; set; }
    }
}
