//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCFloor
    {
        public int VFloorIndex { get; set; }
        public int VFloorID { get; set; }
        public string VFloorName { get; set; }
        public string Vmemo { get; set; }
    }
}
