//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCGate
    {
        public int VgateIndex { get; set; }
        public int VgateID { get; set; }
        public string Vgatename { get; set; }
        public Nullable<int> Register1 { get; set; }
        public string Comname { get; set; }
        public string Vmemo { get; set; }
    }
}
