//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vcheckinout
    {
        public string USERID { get; set; }
        public System.DateTime CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public int VERIFYCODE { get; set; }
        public string SENSORID { get; set; }
        public string ck { get; set; }
        public Nullable<short> Functionkey { get; set; }
        public int TID { get; set; }
        public short door { get; set; }
        public Nullable<short> resv1 { get; set; }
        public Nullable<short> resv2 { get; set; }
        public string Memo1 { get; set; }
        public string Type1 { get; set; }
        public string Badgenumber { get; set; }
    }
}
