//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VcLog
    {
        public int VLindex { get; set; }
        public Nullable<System.DateTime> VINDate { get; set; }
        public Nullable<System.DateTime> VOutDate { get; set; }
        public string VCardID { get; set; }
        public string VcardNo { get; set; }
        public string VCardNos { get; set; }
        public Nullable<int> VCompanyCode { get; set; }
        public string Vcompany { get; set; }
        public Nullable<int> VcontactCode { get; set; }
        public string VContactName { get; set; }
        public Nullable<int> Vpurpose { get; set; }
        public string Vpurposememo { get; set; }
        public Nullable<int> Clearing { get; set; }
        public string VBoxID { get; set; }
        public string VBoxName { get; set; }
        public string VMemo { get; set; }
        public byte[] VPICin { get; set; }
        public byte[] VCardIN { get; set; }
        public byte[] VPicout { get; set; }
        public byte[] VcardOut { get; set; }
        public string VisitorID { get; set; }
        public string VisitorType { get; set; }
        public string VisitorContact { get; set; }
        public string VisitorApprove { get; set; }
        public string VcardType { get; set; }
        public Nullable<int> VFloorId { get; set; }
        public string VFloorname { get; set; }
        public string TotalTime { get; set; }
        public Nullable<int> GateID { get; set; }
        public string GateName { get; set; }
        public string Visitorname { get; set; }
        public string Visitorcompany { get; set; }
        public Nullable<System.DateTime> Lostcarddate { get; set; }
        public Nullable<int> gdoorid { get; set; }
        public string Note1 { get; set; }
        public string VPICinp { get; set; }
        public string VPICoutP { get; set; }
        public string VCARDinp { get; set; }
        public string VCARDoutp { get; set; }
        public string identifycard { get; set; }
        public byte[] Visitorpiccardid { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Badgenumber { get; set; }
        public string Parkingcard { get; set; }
        public string WifiUsername { get; set; }
        public string WifiPassword { get; set; }
        public string Zuser { get; set; }
        public string Euser { get; set; }
        public string Groupaccess { get; set; }
        public string VVisitormobile { get; set; }
        public string Vterncode { get; set; }
        public Nullable<int> Vflag { get; set; }
    }
}
