//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vcomparecontactanduser_Car
    {
        public string Terncode { get; set; }
        public string Id1 { get; set; }
        public string TypeCar { get; set; }
        public Nullable<int> Tamount { get; set; }
        public string Expr1 { get; set; }
        public string Cardcontact_Car { get; set; }
        public Nullable<int> Tcard { get; set; }
        public Nullable<int> remainc { get; set; }
    }
}
