//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VContact
    {
        public int VContactIndex { get; set; }
        public int VContactID { get; set; }
        public string VContactName { get; set; }
        public string VcontacPhone { get; set; }
        public string Vext { get; set; }
        public string Vmemo { get; set; }
        public Nullable<int> VcompanyID { get; set; }
        public string VCompanyName { get; set; }
        public byte[] Vsignature { get; set; }
        public byte[] Vphoto { get; set; }
    }
}
