//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCpanel
    {
        public int Tag1 { get; set; }
        public string PanelControl { get; set; }
        public string PanelControlThai { get; set; }
        public Nullable<int> MSub { get; set; }
        public Nullable<int> Menable { get; set; }
        public Nullable<int> Mselect { get; set; }
        public Nullable<int> Mlevel { get; set; }
    }
}
