//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCPurpose
    {
        public int VpurposeIndex { get; set; }
        public int VPurposeID { get; set; }
        public string Vpurpose { get; set; }
        public string Vmemo { get; set; }
    }
}
