//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerifyCode
    {
        public int VerifyId { get; set; }
        public string Engmean { get; set; }
        public string Thaimean { get; set; }
        public string CustEngmean { get; set; }
        public string CustThaimean { get; set; }
        public Nullable<int> Showmean { get; set; }
        public Nullable<int> nAlarmSet { get; set; }
    }
}
