//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vlocationzoneparking_Tuesday
    {
        public int Zoneid1 { get; set; }
        public string zDesc { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> Loc_Id { get; set; }
        public Nullable<int> Timein1 { get; set; }
        public Nullable<int> ID1 { get; set; }
        public string Name { get; set; }
        public Nullable<int> Mont1 { get; set; }
        public Nullable<int> Tuet1 { get; set; }
        public Nullable<int> Wedt1 { get; set; }
        public Nullable<int> Thut1 { get; set; }
        public Nullable<int> Frit1 { get; set; }
        public Nullable<int> Satt1 { get; set; }
        public Nullable<int> Sunt1 { get; set; }
        public Nullable<int> Holt1 { get; set; }
        public Nullable<int> id { get; set; }
        public string Expr2 { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
