//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMotor_ofcompany
    {
        public string InOutTran_ID { get; set; }
        public string Scr_No { get; set; }
        public string CscMain_ID { get; set; }
        public string Rabbit_ID { get; set; }
        public Nullable<int> UseMin { get; set; }
        public string CarID { get; set; }
        public Nullable<int> Site_Id { get; set; }
        public Nullable<int> Loc_ID { get; set; }
        public Nullable<int> Equip_ID { get; set; }
        public Nullable<short> Trans_Event { get; set; }
        public Nullable<int> LastLoc_ID { get; set; }
        public Nullable<int> LastEquip_id { get; set; }
        public Nullable<int> Rides_Remain { get; set; }
        public Nullable<decimal> AddDeduct_Val { get; set; }
        public Nullable<decimal> ParkingTime_Val { get; set; }
        public Nullable<System.DateTime> Indate { get; set; }
        public Nullable<System.DateTime> Outdate { get; set; }
        public Nullable<decimal> SumTotal { get; set; }
        public Nullable<int> HourTotal { get; set; }
        public string CustNo { get; set; }
        public Nullable<int> Typecard { get; set; }
        public string StampCode1 { get; set; }
        public string StampCode2 { get; set; }
        public string StampCode3 { get; set; }
        public string StampCode4 { get; set; }
        public string ZUser { get; set; }
        public string EUser { get; set; }
        public string FlagPost { get; set; }
        public string FlagStatus { get; set; }
        public Nullable<System.DateTime> ParkTime { get; set; }
        public string Paymonth { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public string CustomerID { get; set; }
        public string Lost_Card { get; set; }
        public string Lost_Slip { get; set; }
        public Nullable<decimal> VStamp1 { get; set; }
        public Nullable<decimal> VStamp2 { get; set; }
        public Nullable<decimal> VStamp3 { get; set; }
        public Nullable<decimal> VStamp4 { get; set; }
        public string Mark_rec { get; set; }
        public Nullable<int> StampMin1 { get; set; }
        public Nullable<int> StampMin2 { get; set; }
        public Nullable<int> StampMin3 { get; set; }
        public Nullable<int> StampMin4 { get; set; }
        public Nullable<decimal> Lost_Card_Fine { get; set; }
        public Nullable<decimal> Lost_Slip_Fine { get; set; }
        public Nullable<System.DateTime> DateIn1 { get; set; }
        public Nullable<System.DateTime> DateOut1 { get; set; }
        public Nullable<System.TimeSpan> TimeIn1 { get; set; }
        public Nullable<System.TimeSpan> TimeOut1 { get; set; }
        public string Picin1 { get; set; }
        public string Picin2 { get; set; }
        public string Picin3 { get; set; }
        public string Picout1 { get; set; }
        public string Picout2 { get; set; }
        public string Picout3 { get; set; }
        public Nullable<int> CompleteFlag { get; set; }
        public Nullable<int> Person_ID1 { get; set; }
        public Nullable<System.DateTime> Last_Upd1 { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public Nullable<int> sf { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public string VNIDFNameT { get; set; }
        public string VNIDLNameT { get; set; }
        public string VNIDFNameE { get; set; }
        public string VNIDLNameE { get; set; }
        public string VNID { get; set; }
        public Nullable<System.DateTime> VNIDBD { get; set; }
        public Nullable<System.DateTime> VNIDExpireDate { get; set; }
        public Nullable<System.DateTime> VNIDIssueDate { get; set; }
        public string VNIDaddress { get; set; }
        public string VContact { get; set; }
        public string VDepartment { get; set; }
        public string VContact_IL { get; set; }
        public string Picin4 { get; set; }
        public string Picout4 { get; set; }
        public string INV_ID { get; set; }
        public Nullable<int> INVF { get; set; }
        public string Sh_id { get; set; }
        public string Visitorcompany { get; set; }
        public string Visitorgroup { get; set; }
        public string Areaid { get; set; }
        public string Areadesc { get; set; }
        public Nullable<int> Paytype { get; set; }
        public string cartype { get; set; }
        public Nullable<int> cashpay { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<int> CompanyMotor { get; set; }
        public string TernCode { get; set; }
    }
}
