//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vparking_detail
    {
        public string InOutTran_ID { get; set; }
        public string CscMain_ID { get; set; }
        public string Scr_No { get; set; }
        public Nullable<System.DateTime> Indate { get; set; }
        public Nullable<System.DateTime> Outdate { get; set; }
        public Nullable<System.DateTime> DateIn1 { get; set; }
        public Nullable<System.TimeSpan> TimeIn1 { get; set; }
        public Nullable<System.DateTime> DateOut1 { get; set; }
        public Nullable<System.TimeSpan> TimeOut1 { get; set; }
        public Nullable<int> Typecard { get; set; }
        public Nullable<int> HourTotal { get; set; }
        public Nullable<int> cashpay { get; set; }
        public string cartype { get; set; }
        public Nullable<int> rangetime { get; set; }
    }
}
