//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vsummaryallincome_byyear_horizontal
    {
        public int year1 { get; set; }
        public string Cartype { get; set; }
        public string Terncode { get; set; }
        public string Companyname { get; set; }
        public string Typecal { get; set; }
        public int No1 { get; set; }
        public string List1 { get; set; }
        public int month1 { get; set; }
        public Nullable<int> totalcar1 { get; set; }
        public Nullable<decimal> totalamount1 { get; set; }
        public Nullable<int> totalcar2 { get; set; }
        public Nullable<decimal> totalamount2 { get; set; }
        public Nullable<int> totalcar3 { get; set; }
        public Nullable<decimal> totalamount3 { get; set; }
        public Nullable<int> totalcar4 { get; set; }
        public Nullable<decimal> totalamount4 { get; set; }
        public Nullable<int> totalcar5 { get; set; }
        public Nullable<decimal> totalamount5 { get; set; }
        public Nullable<int> totalcar6 { get; set; }
        public Nullable<decimal> totalamount6 { get; set; }
        public Nullable<int> totalcar7 { get; set; }
        public Nullable<decimal> totalamount7 { get; set; }
        public Nullable<int> totalcar8 { get; set; }
        public Nullable<decimal> totalamount8 { get; set; }
        public Nullable<int> totalcar9 { get; set; }
        public Nullable<decimal> totalamount9 { get; set; }
        public Nullable<int> totalcar10 { get; set; }
        public Nullable<decimal> totalamount10 { get; set; }
        public Nullable<int> totalcar11 { get; set; }
        public Nullable<decimal> totalamount11 { get; set; }
        public Nullable<int> totalcar12 { get; set; }
        public Nullable<decimal> totalamount12 { get; set; }
    }
}
