//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vsummaryallincome_byyear
    {
        public int Month1 { get; set; }
        public int year1 { get; set; }
        public string Cartype { get; set; }
        public string Terncode { get; set; }
        public string Companyname { get; set; }
        public string Typecal { get; set; }
        public int No1 { get; set; }
        public string List1 { get; set; }
        public Nullable<int> right1 { get; set; }
        public Nullable<int> billcar { get; set; }
        public Nullable<decimal> billamouunt { get; set; }
        public Nullable<int> cashcar { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public Nullable<int> totalcar { get; set; }
        public Nullable<decimal> totalamount { get; set; }
    }
}
