//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vtotalcard_motor
    {
        public string Scr_No { get; set; }
        public string CscMain_ID { get; set; }
        public string Rabbit_ID { get; set; }
        public string Scr_no7b { get; set; }
        public string CustNo { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Sex { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Terncode { get; set; }
        public string TernSubCode { get; set; }
        public Nullable<int> CardType_ID { get; set; }
        public string CarId { get; set; }
        public string CarModel { get; set; }
        public string Carcolor { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> Issuesite_id { get; set; }
        public Nullable<int> IssueLoc_ID { get; set; }
        public Nullable<int> IssueLoc_ID2 { get; set; }
        public Nullable<int> IssueEquip_ID { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> FirstUse { get; set; }
        public Nullable<System.DateTime> LastUse { get; set; }
        public Nullable<int> LastLoc_ID { get; set; }
        public string Last_Equip_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public string InitCredit { get; set; }
        public Nullable<decimal> RemainCredit { get; set; }
        public Nullable<decimal> Earnest { get; set; }
        public Nullable<int> TotalUse { get; set; }
        public Nullable<int> TotalRides { get; set; }
        public Nullable<decimal> TotalDeductCredit { get; set; }
        public Nullable<decimal> TotalAddCredit { get; set; }
        public Nullable<decimal> TotalBonusCredit { get; set; }
        public string Occupied { get; set; }
        public string Remark { get; set; }
        public string Lastcscmain_id { get; set; }
        public string CardContact { get; set; }
        public string Cartype { get; set; }
        public string CardType { get; set; }
        public string Activecard { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public string Pay { get; set; }
        public string Statuspay { get; set; }
        public string Lastscr_no { get; set; }
        public Nullable<System.DateTime> syndate { get; set; }
        public Nullable<int> sf { get; set; }
        public string Groupmember { get; set; }
        public Nullable<int> statusaccess { get; set; }
        public Nullable<int> workmode { get; set; }
        public Nullable<int> groupaccess { get; set; }
        public string CardActive { get; set; }
    }
}
