//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuserinout
    {
        public string USERID { get; set; }
        public string BADGENUMBER { get; set; }
        public string SSN { get; set; }
        public string refno { get; set; }
        public System.DateTime CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public string SENSORID { get; set; }
        public int TID { get; set; }
        public Nullable<short> Functionkey { get; set; }
        public int VERIFYCODE { get; set; }
        public string ck { get; set; }
        public short door { get; set; }
        public string TFirstname { get; set; }
        public string TLastname { get; set; }
        public string TernCode { get; set; }
        public string TernSubcode { get; set; }
        public Nullable<int> Positioninfo { get; set; }
        public string Memo1 { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> nTitle { get; set; }
    }
}
