//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VvisitorDetail
    {
        public int VisitorID { get; set; }
        public string VisitorName { get; set; }
        public string Visitormobile { get; set; }
        public string Visitorphone { get; set; }
        public string VisitorCompany { get; set; }
        public string VisitorAddress { get; set; }
        public string Identifycard { get; set; }
        public byte[] Visitorpic { get; set; }
        public string Visitorpicpath { get; set; }
        public string Vmemo { get; set; }
    }
}
