//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vvisitor
    {
        public Nullable<int> GateID { get; set; }
        public Nullable<int> day1 { get; set; }
        public Nullable<int> month1 { get; set; }
        public Nullable<int> year1 { get; set; }
        public int VLindex { get; set; }
    }
}
